language: rust

sudo: false

cache:
  directories:
    - $HOME/SDL2
    - $HOME/SDL2_ttf
    - $HOME/.cargo
    - $HOME/artifacts

before_install:
  - mkdir -p "$HOME/artifacts"
  - export "PATH=$PATH:$HOME/SDL2/bin"
  - export "LIBRARY_PATH=$LIBRARY_PATH:$HOME/SDL2/lib:$HOME/SDL2_ttf/lib"
  - export "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/SDL2/lib:$HOME/SDL2_ttf/lib"
  - if [ ! -d "$HOME/SDL2/lib" ]; then wget https://www.libsdl.org/release/SDL2-2.0.3.tar.gz -O ~/SDL2.tar.gz && tar -xzvf ~/SDL2.tar.gz -C ~/ && mkdir ~/sdl-build && cd ~/sdl-build && ~/SDL2-2.0.3/configure --prefix=$HOME/SDL2 && make && make install; else echo 'Using cached SDL2 build directory.'; fi
  - if [ ! -d "$HOME/SDL2_ttf/lib" ]; then wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.tar.gz -O ~/SDL2_ttf.tar.gz && tar -xzvf ~/SDL2_ttf.tar.gz -C ~/ && mkdir ~/sdl-ttf-build && cd ~/sdl-ttf-build && ~/SDL2_ttf-2.0.12/configure --prefix=$HOME/SDL2_ttf && make && make install; else echo 'Using cached SDL2_ttf build directory.'; fi
  - cd $TRAVIS_BUILD_DIR
  - export ARTIFACT_CACHE="$HOME/artifacts/$(rustc --version | sed 's/^rustc \([^ ]*\).*$/\1/g')"
  - mkdir -p "$ARTIFACT_CACHE"
  - rm -rf target
  - ln -s "$ARTIFACT_CACHE" target

rust:
  - stable
  - beta
  - nightly

script:
  - rustc --version
  - cargo build
  - make test

