[package]
name = "gfx"
version = "0.0.1"
authors = ["Cristian Cobzarenco <cristi.cobzarenco@gmail.com>"]

[lib]
name = "gfx"
path = "lib.rs"

[dependencies.math]
path = "../math"

[dependencies.common]
path = "../common"

[dependencies]
log = "*"
libc = "*"
sdl2 = "*"
glium = "*"
glium_sdl2 = "*"
